"""add topic_reviews for spaced repetition

Revision ID: f40608909dfc
Revises: b1765d6bec9c
Create Date: 2026-09-12 05:46:26.068818
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f40608909dfc'
down_revision: Union[str, None] = 'b1765d6bec9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic', name='uq_topic_reviews_user_topic')
    )
    op.create_index(op.f('ix_topic_reviews_due_at'), 'topic_reviews', ['due_at'], unique=False)
    op.create_index(op.f('ix_topic_reviews_topic'), 'topic_reviews', ['topic'], unique=False)
    op.create_index(op.f('ix_topic_reviews_user_id'), 'topic_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_reviews_user_id'), table_name='topic_reviews')
    op.drop_index(op.f('ix_topic_reviews_topic'), table_name='topic_reviews')
    op.drop_index(op.f('ix_topic_reviews_due_at'), table_name='topic_reviews')
    op.drop_table('topic_reviews')
    # ### end Alembic commands ###
